version: '3'
services:
  app:
      build: .
      ports:
       - "4000:4000"
      command: npm run start
      volumes:
        - .:/src
        - nodemodules:/src/node_modules
        - ./logs:/src/logs
      restart: always
      networks: 
      - custom_host
  database:
    build: db
    ports:
     - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes: 
      - pgdata:/var/lib/postgresql/data/pgdata
    restart: always
    networks: 
      - custom_host
    depends_on: 
      - app
volumes:
  nodemodules: {}
  pgdata: {}
networks:
  custom_host:
    driver: bridge



