version: '3'
services:
  app:
    build: .
    command: npm run start
    ports:
      - 4000:4000
    volumes:
      - .:/src
      - nodemodules:/src/node_modules
      - ./logs:/src/logs
    restart: always
  database:
    build: db
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 11111
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes: 
      - pgdata:/var/lib/postgresql/data/pgdata
    restart: always
volumes:
  nodemodules: {}
  pgdata: {}

