version: '3'
services:
  database:
    build: db
    ports: 
      - "${PG_PORT}:${PG_PORT}"
    environment:
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes: 
      - pgdata:/var/lib/postgresql/data/pgdata
    restart: always
volumes:
  nodemodules: {}
  pgdata: {}



