version: '3'
services:
  app:
    build: .
    command: npm run start
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/src
      - nodemodules:/src/node_modules
      - ./logs:/src/logs
    restart: always
    networks: 
      - net
  database:
    build: db
    ports: 
      - "${PG_PORT}:${PG_PORT}"
    environment:
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes: 
      - pgdata:/var/lib/postgresql/data/pgdata
    restart: always
    networks: 
      - net
    depends_on: 
      - app
volumes:
  nodemodules: {}
  pgdata: {}
networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: "${SUBNET_ID}"



